pipeline {
    agent any
    stages {
        stage("Build") {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mv test'
            }
        }
        stage('Emulate Program') {
            steps {
                sh './jenkins/scripts/emulate-something.sh'
            }
        }
    }
}