pipeline {
    agent any
    stages {
        stage("Intro") {
            steps {
                echo "To leci z repo z GitHub'a"
            }
        }
        stage("Stage 1") {
            steps {
                echo "This is stage 1"
            }
        }
        stage("Stage 2") {
            steps {
                echo "This is stage 2"
            }
        }
        stage("Stage 3") {
            steps {
                echo "This is stage 3"
            }
        }
        stage("Stage 4") {
            steps {
                echo "This is stage 4"
            }
        }
        stage("Stage 5") {
            steps {
                echo "This is stage 5"
            }
        }
    }
}